version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    restart: always
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    volumes:
      - /server_app/node_modules
      - ./server:/server_app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /worker/node_modules
      - ./worker:/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    environment:
      - WDS_SOCKET_PORT=0
    build: 
      context: ./client/
      dockerfile: Dockerfile.dev
    volumes:
      - /frontend/node_modules
      - ./client:/frontend
  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - api
      - client